/**
 * Pixel pattern library - the shared "real designs" asset for the tool pages.
 *
 * Every pattern is a hand-drawn pixel design (ASCII grid + palette), tagged
 * with the crafts it suits. This replaces the math-generated stripes/checkers
 * that made the generator demos look programmer-made: a user landing on a
 * craft tool page sees an actual finished artifact within 3 seconds.
 *
 * Grid rows must all be the same width; palette maps a char -> hex. '.' is
 * always transparent.
 */

export type PixelCraft = 'bead' | 'cross-stitch' | 'bracelet' | 'diamond' | 'knitting' | 'sprite';
export type PatternCategory = 'animal' | 'nature' | 'food' | 'symbol' | 'game';

export interface PixelPattern {
  id: string;
  name: string;
  category: PatternCategory;
  difficulty: 'easy' | 'medium';
  crafts: PixelCraft[];
  palette: Record<string, string>;
  grid: string[];
}

export const PIXEL_PATTERNS: PixelPattern[] = [
  {
    id: 'cat',
    name: 'Cat',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', F: '#F2A65A', T: '#FF8FA3', E: '#2E7D32', W: '#FFFFFF', P: '#FF8FA3' },
    grid: [
      '..OO........OO..',
      '.OFFO......OFFO.',
      '.OFTOOOOOOOOTFO.',
      '..OFFFFFFFFFFO..',
      '.OFFEFFFFFFEFFO.',
      '.OFFEFFFFFFEFFO.',
      '.OFFFFFWWWFFFFO.',
      '.OFFFFWWWWFFFFO.',
      '.OFFFFWPWFFFFFO.',
      '..OFFWWWWWWFFO..',
      '..OFFFFWWFFFFO..',
      '...OFFFFFFFFO...',
      '....OFFFFFFO....',
      '....OFFOOFFO....',
      '.....OOOOOO.....',
      '................',
    ],
  },
  {
    id: 'panda',
    name: 'Panda',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', W: '#FFFFFF' },
    grid: [
      '..OOO......OOO..',
      '.OOOOO....OOOOO.',
      '.OOOOOOOOOOOOOO.',
      '.OWWWWWWWWWWWWO.',
      '.OWWOOWWWWOOWWO.',
      '.OWWOOWWWWOOWWO.',
      '.OWWWWWOOWWWWWO.',
      '.OWWWWWWWWWWWWO.',
      '..OWWWWOOWWWWO..',
      '..OWWWWWWWWWWO..',
      '...OWWWWWWWWO...',
      '....OWWWWWWO....',
      '.....OOOOOO.....',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'penguin',
    name: 'Penguin',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', W: '#FFFFFF', Y: '#F2A65A' },
    grid: [
      '....OOOOOOOO....',
      '...OOOOOOOOOO...',
      '...OOWOOOOWOO...',
      '...OOOYYYYOOO...',
      '..OOOOOYYOOOOO..',
      '..OOOOWWWWOOOO..',
      '.OOOOWWWWWWOOOO.',
      '.OOOOWWWWWWOOOO.',
      '.OOOOWWWWWWOOOO.',
      '.OOOOWWWWWWOOOO.',
      '..OOOOWWWWOOOO..',
      '..OOOOOOOOOOOO..',
      '...OYYOOOOYYO...',
      '....YY....YY....',
      '................',
      '................',
    ],
  },
  {
    id: 'bunny',
    name: 'Bunny',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', W: '#FFFFFF', P: '#FF8FA3' },
    grid: [
      '...OOO...OOO....',
      '...OWO...OWO....',
      '...OWO...OWO....',
      '...OPO...OPO....',
      '..OOOOOOOOOOO...',
      '..OWWWWWWWWWO...',
      '.OWWOWWWWWWOWWO.',
      '.OWWWWWPPWWWWWO.',
      '..OWWWWPPWWWWO..',
      '..OWWWWWWWWWWO..',
      '...OWWWWWWWWO...',
      '....OWWWWWWO....',
      '.....OOOOOO.....',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'bear',
    name: 'Bear',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', B: '#A9744F', M: '#E8C9A0' },
    grid: [
      '...OO......OO...',
      '..OBBO....OBBO..',
      '..OBBOOOOOOBBO..',
      '.OBBBBBBBBBBBBO.',
      '.OBBOBBBBBBOBBO.',
      '.OBBBBMMMMBBBBO.',
      '.OBBBMMOOMMBBBO.',
      '.OBBBBMMMMBBBBO.',
      '..OBBBBBBBBBBO..',
      '...OBBBBBBBBO...',
      '....OOOOOOOO....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'frog',
    name: 'Frog',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'sprite'],
    palette: { O: '#262626', G: '#6BBF59', W: '#FFFFFF' },
    grid: [
      '..OOO......OOO..',
      '.OGWGO....OGWGO.',
      '.OGGGOOOOOOGGGO.',
      '..OGGGGGGGGGGO..',
      '..OGWOGGGGWOGO..',
      '.OGGGGGGGGGGGGO.',
      '.OGGGGOOOGGGGGO.',
      '.OGGGGGGGGGGGGO.',
      '..OGGGGGGGGGGO..',
      '...OOOOOOOOOO...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'owl',
    name: 'Owl',
    category: 'animal',
    difficulty: 'medium',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#262626', B: '#8B6BB1', W: '#FFFFFF', Y: '#F2A65A' },
    grid: [
      '..OO........OO..',
      '.OBOO......OOBO.',
      '.OBBOOOOOOOOBBO.',
      '.OBBWWBBBWWBBBO.',
      'OBBWOWBBBWOWBBBO',
      'OBBWWWBBBWWWBBBO',
      'OBBBBBYYYBBBBBBO',
      'OBBBBBWWWBBBBBBO',
      '.OBBBWWWWWBBBBO.',
      '.OBBBBWWWBBBBBO.',
      '..OOBBBBBBBBOO..',
      '...OOOOOOOOOO...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'bee',
    name: 'Bee',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { Y: '#F5C542', K: '#262626', W: '#E8F4FA' },
    grid: [
      '....WW....WW....',
      '...WWWW..WWWW...',
      '....KKKKKKKK....',
      '...KYYYYYYYYK...',
      '..KYKKYYYYKKYK..',
      '..KYYYKKKKYYYK..',
      '..KYYYYYYYYYYK..',
      '..KYKKYYYYKKYK..',
      '...KYYYYYYYYK...',
      '....KKKKKKKK....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    category: 'animal',
    difficulty: 'medium',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { P: '#FF8FA3', U: '#9C6BFF', K: '#262626' },
    grid: [
      'PP..........PP..',
      'PPPP......PPPP..',
      '.PPPPPKKPPPPP...',
      '.PPPPPKKPPPPP...',
      '..PPPPKKPPPP....',
      '...PPKKKKPP.....',
      '....UKKKKU......',
      '.....KKKK.......',
      '....UKKKU.......',
      '...UUUUUU.......',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'fish',
    name: 'Fish',
    category: 'animal',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'sprite'],
    palette: { B: '#2F9EE8', Y: '#F5C542', W: '#FFFFFF' },
    grid: [
      '..........YY....',
      '...BBBBBB..YY...',
      '..BBBBBBBB.YY...',
      '.BBWBBBBBBBYY...',
      '.BBBWBBBBBBYY...',
      '.BBBBBBBBBBYY...',
      '..BBBBBBBB.YY...',
      '...BBBBBB..YY...',
      '..........YY....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'bracelet', 'diamond', 'knitting'],
    palette: { R: '#E53935', O: '#FF9800', Y: '#F5C542', G: '#4CAF50', B: '#2F9EE8' },
    grid: [
      '.....RRRRRR.....',
      '...RROOOOOORR...',
      '..ROOYYYYYYOOR..',
      '.ROYYGGGGGGYYOR.',
      '.ROYGGBBBBBGGYOR',
      'ROYGGBBBBBBGGYOR',
      'ROYGBBBBBBBBGYOR',
      'ROYGBBBBBBBBGYOR',
      'ROYGGBBBBBBGGYOR',
      '.ROYYGGGGGGYYOR.',
      '..ROOYYYYYYOOR..',
      '...RROOOOOORR...',
      '.....RRRRRR.....',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'flower',
    name: 'Flower',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'bracelet', 'diamond', 'knitting'],
    palette: { P: '#FF8FA3', Y: '#F5C542', G: '#4CAF50' },
    grid: [
      '....PP....PP....',
      '...PPPP..PPPP...',
      '...PPPPPPPPPP...',
      '..PPPPYYYYPPPP..',
      '..PPPYYYYYYPPP..',
      '..PPPYYYYYYPPP..',
      '..PPPPYYYYPPPP..',
      '...PPPPPPPPPP...',
      '...PPPP..PPPP...',
      '....PP....PP....',
      '......GG........',
      '..G...GG...G....',
      '..GG..GG..GG....',
      '...GGG..GGG.....',
      '......GG........',
      '.....GGG........',
    ],
  },
  {
    id: 'tulip',
    name: 'Tulip',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'knitting'],
    palette: { R: '#E53935', G: '#4CAF50' },
    grid: [
      '...R..RR..R.....',
      '...RRRRRRRR.....',
      '...RRRRRRRR.....',
      '....RRRRRR......',
      '.....RRRR.......',
      '......GG........',
      '..LLL..GG..LLL..',
      '...LLL.GG.LLL...',
      '....LLLGGLLL....',
      '......GG........',
      '......GG........',
      '................',
      '................',
      '................',
      '................',
      '................',
    ].map((row) => row.replace(/L/g, 'G')),
  },
  {
    id: 'pine-tree',
    name: 'Pine Tree',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'knitting'],
    palette: { G: '#2E7D32', T: '#8B5A2B' },
    grid: [
      '.......GG.......',
      '......GGGG......',
      '.....GGGGGG.....',
      '....GGGGGGGG....',
      '...GGGGGGGGGG...',
      '..GGGGGGGGGGGG..',
      '....GGGGGGGG....',
      '...GGGGGGGGGG...',
      '..GGGGGGGGGGGG..',
      '.GGGGGGGGGGGGGG.',
      '..GGGGGGGGGGGG..',
      '......TTTT......',
      '......TTTT......',
      '......TTTT......',
      '................',
      '................',
    ],
  },
  {
    id: 'sun',
    name: 'Sun',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'knitting'],
    palette: { Y: '#F5C542', O: '#FF9800' },
    grid: [
      '..O....OO....O..',
      '....O.YYYY.O....',
      '.O..OYYYYYYO..O.',
      '...OYYYYYYYYO...',
      'OOOYYYYYYYYYYOOO',
      'OOOYYYYYYYYYYOOO',
      '...OYYYYYYYYO...',
      '.O..OYYYYYYO..O.',
      '....O.YYYY.O....',
      '..O....OO....O..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'moon',
    name: 'Moon',
    category: 'nature',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond', 'knitting'],
    palette: { Y: '#F5C542' },
    grid: [
      '....YYYYY.......',
      '..YYYYYYYYYY....',
      '.YYYYYYYYYYYY...',
      '.YYYYYYYYYYYYY..',
      'YYYYYYYYYYYYY...',
      'YYYYYYYYYYYY....',
      'YYYYYYYYYYYY....',
      'YYYYYYYYYYYYY...',
      '.YYYYYYYYYYYYY..',
      '.YYYYYYYYYYYY...',
      '..YYYYYYYYYY....',
      '....YYYYY.......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'pizza',
    name: 'Pizza Slice',
    category: 'food',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { C: '#F2CC8F', Y: '#F5C542', R: '#E53935' },
    grid: [
      '..CCCCCCCCCCCC..',
      '..CYYYYYYYYYYC..',
      '..CYYRYYYYRYC...',
      '..CYYYYYYYYYC...',
      '...CYYRYYYYC....',
      '...CYYYYYYC.....',
      '....CYYYYC......',
      '....CYRYC.......',
      '.....CYC........',
      '......C.........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'food',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { R: '#FB3640', K: '#262626', W: '#FFFFFF', G: '#2E7D32' },
    grid: [
      '....RRRRRRRR....',
      '..RRRRKRRKRRRR..',
      '.RRKRRRRRRKRRR..',
      '.RRRRKRRKRRRRR..',
      '.RRRRRRRRRRRRR..',
      '.RRKRRRRKRRRRR..',
      '..RRRRRRRRRRRR..',
      '..WWWWWWWWWWWW..',
      '...GGGGGGGGGG...',
      '....GGGGGGGG....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'ice-cream',
    name: 'Ice Cream',
    category: 'food',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { C: '#D9A066', W: '#FFF8E7', P: '#FF8FA3', R: '#E53935' },
    grid: [
      '......RR........',
      '.....PPPP.......',
      '....WWWWWW......',
      '...WWWWWWWW.....',
      '...PWWWWWWP.....',
      '..WWWWWWWWWW....',
      '..PWWWWWWWWP....',
      '..WWWWWWWWWW....',
      '...CCCCCCCC.....',
      '...CCCCCCCC.....',
      '....CCCCCC......',
      '.....CCCCC......',
      '......CCC.......',
      '.......C........',
      '................',
      '................',
    ],
  },
  {
    id: 'donut',
    name: 'Donut',
    category: 'food',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { D: '#E8A87C', P: '#FF8FA3', S: '#4ECDC4' },
    grid: [
      '....DDDDDDDD....',
      '..DDPPPPPPPPDD..',
      '.DDPPPSPPSPPDDD.',
      '.DPPSPPPPPPSPPD.',
      'DDPPPPPPPPPPPPDD',
      'DDPPSPPPPPPSPPDD',
      '.DPPPP....PPPPD.',
      '.DPPP......PPPD.',
      '.DPPP......PPPD.',
      '.DPPPP....PPPPD.',
      'DDPPPPPPPPPPPPDD',
      '.DPPSPPPPPPSPPD.',
      '.DDPPPSPPSPPDDD.',
      '..DDPPPPPPPPDD..',
      '....DDDDDDDD....',
      '................',
    ],
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    category: 'food',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'diamond'],
    palette: { O: '#E8722C', D: '#C4501D', G: '#3E7C3A' },
    grid: [
      '.......GG.......',
      '.......GG.......',
      '..OOOOOOOOOOOO..',
      '.OOODOOOOODOOOO.',
      'OOOODOOOOOODOOOO',
      'OOOODOOOOOODOOOO',
      'OOOODOOOOOODOOOO',
      'OOOODOOOOOODOOOO',
      '.OOODOOOOODOOOO.',
      '.OOODOOOOODOOOO.',
      '..OOOOOOOOOOOO..',
      '...OOOOOOOOOO...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'symbol',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'bracelet', 'diamond', 'knitting'],
    palette: { W: '#7FD8E8' },
    grid: [
      '.......W........',
      '..W....W....W...',
      '...W...W...W....',
      '....W..W..W.....',
      '.....W.W.W......',
      '......WWW.......',
      'WWWWWWWWWWWWWWWW',
      '......WWW.......',
      '.....W.W.W......',
      '....W..W..W.....',
      '...W...W...W....',
      '..W....W....W...',
      '.......W........',
      '................',
      '................',
      '................',
    ],
  },
  {
    id: 'crown',
    name: 'Crown',
    category: 'symbol',
    difficulty: 'easy',
    crafts: ['bead', 'cross-stitch', 'bracelet', 'diamond', 'knitting'],
    palette: { Y: '#F5C542', R: '#E53935' },
    grid: [
      'Y....Y..Y....Y..',
      'Y....Y..Y....Y..',
      'YY...Y..Y...YY..',
      'YYY..YYYYYY..YYY',
      'YYYYYYYYYYYYYYYY',
      'YYYYYYYYYYYYYYYY',
      'YRYYYYRYYYYRYYYY',
      'YYYYYYYYYYYYYYYY',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
];

/** Find a pattern by id. */
export function getPixelPattern(id: string): PixelPattern | undefined {
  return PIXEL_PATTERNS.find((p) => p.id === id);
}

/** Patterns suited to a craft, in library order. */
export function patternsForCraft(craft: PixelCraft): PixelPattern[] {
  return PIXEL_PATTERNS.filter((p) => p.crafts.includes(craft));
}

/* ── Grid stats + rendering (pure, no DOM) ─────────────────────────────── */

export interface PatternStats {
  cols: number;
  rows: number;
  /** hex -> cell count, sorted by count desc. */
  counts: { hex: string; count: number }[];
  totalCells: number;
}

export function patternStats(pattern: PixelPattern): PatternStats {
  const rows = pattern.grid.length;
  const cols = pattern.grid[0]?.length ?? 0;
  const counts = new Map<string, number>();
  let totalCells = 0;
  for (const row of pattern.grid) {
    for (const ch of row) {
      if (ch === '.' || ch === ' ') continue;
      const hex = pattern.palette[ch];
      if (!hex) continue;
      counts.set(hex, (counts.get(hex) ?? 0) + 1);
      totalCells++;
    }
  }
  return {
    cols,
    rows,
    totalCells,
    counts: [...counts.entries()]
      .map(([hex, count]) => ({ hex, count }))
      .sort((a, b) => b.count - a.count),
  };
}
