import type { Section } from "@template/ui";

export const props = {
    section: {
      id: "cleaner",
      title: "AI Text Cleaner",
      description: "Humanize and clean AI-generated text.",
    },
    input: "The quick brown fox jumps over the lazy dog. Moreover, it is important to note that the team was able to complete the task efficiently.",
    onInputChange: () => {},
    mode: "humanize",
    onModeChange: () => {},
    tone: "natural",
    onToneChange: () => {},
    length: "same",
    onLengthChange: () => {},
    strength: "standard",
    onStrengthChange: () => {},
    options: ["trimWhitespace", "normalizeDashes"],
    onOptionsChange: () => {},
    outputView: "changes",
    output: "The quick brown fox jumps over the lazy dog. The team completed the task efficiently.",
    inputCount: 142,
    outputCount: 118,
    error: "",
    copied: false,
    shareCopied: false,
    busy: false,
    showAiHint: true,
    activeDiffParts: [
      { value: "The quick brown fox jumps over the lazy dog. " },
      { value: "Moreover, it is important to note that ", removed: true },
      { value: "The team completed the task efficiently." },
    ],
    activeHasChanges: true,
    analyzeResult: null,
    isRewriting: false,
    fallbackNotice: false,
    showAdvancedOptions: false,
    onToggleAdvancedOptions: () => {},
    contextMode: "auto",
    detectedContextMode: "general",
    typeLabels: { repetition: "Repetition" },
    severityLabels: { high: "High", medium: "Medium", low: "Low" },
    onClear: () => {},
    onCopy: () => {},
    onAnalyze: () => {},
    onFixWithAi: () => {},
    onContextModeChange: () => {},
    onExportMarkdown: () => {},
    onExportPdf: () => {},
    onShareLink: () => {},
    t: (key: string) => key,
    modeOptions: [
      { value: "humanize", label: "Humanize" },
      { value: "simplify", label: "Simplify" },
      { value: "grammar", label: "Grammar" },
    ],
    toneOptions: [
      { value: "natural", label: "Natural" },
      { value: "confident", label: "Confident" },
    ],
    lengthOptions: [
      { value: "same", label: "Same" },
      { value: "shorter", label: "Shorter" },
    ],
    strengthOptions: [
      { value: "light", label: "Light" },
      { value: "standard", label: "Standard" },
      { value: "strong", label: "Strong" },
    ],
    optionLabels: { trimWhitespace: "Trim whitespace", normalizeDashes: "Normalize dashes" },
  };
