import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Design Studio",
    title: "Design your thumbnail",
    description: "Pick a template, tweak the design, and export.",
    badges: [{ label: "Free", tone: "free" }],
    meta: [{ icon: "info", text: "No watermark" }],
    heroCanvasBadge: "Live preview",
    heroCanvasTag: "1920 × 1080",
    heroCanvas: { title: "Your title here", subtitle: "Subtitle", swatch: ["#7c4fff", "#ff6363"], accent: "#7c4fff" },
    stage: "design",
    onStageChange: () => {},
    stages: [
      { key: "source", label: "Source", icon: "upload" },
      { key: "templates", label: "Templates", icon: "grid" },
      { key: "design", label: "Design", icon: "wand" },
      { key: "export", label: "Export", icon: "download" },
    ],
    stageOfLabel: "of",
    stageTotalLabel: "4",
    sourceTitle: "Upload your image",
    sourceHint: "PNG, JPG up to 10MB",
    continueLabel: "Continue",
    hasSource: true,
    sourcePreview: "",
    onFile: () => {},
    onUrl: () => {},
    onSample: () => {},
    templatesTitle: "Choose a template",
    useTemplateLabel: "Use template",
    appliedLabel: "Applied",
    skipLabel: "Skip",
    templateCategories: [{ key: "youtube", label: "YouTube" }, { key: "x", label: "X / Twitter" }],
    templates: [
      { id: "t1", name: "Bold", category: "youtube", description: "High contrast", design: { bgColor: "#111", rounded: 0, showBorder: false, borderWidth: 0, borderColor: "#000", imageFit: "cover", shadow: true, title: "Bold", subtitle: "Subtitle", titleColor: "#fff", titleSize: 72, titleAlign: "left", textY: 60, effects: { brightness: 100, contrast: 110, saturation: 110 } }, swatch: ["#7c4fff", "#fff"], accent: "#7c4fff" },
      { id: "t2", name: "Clean", category: "x", description: "Minimal", design: { bgColor: "#fff", rounded: 12, showBorder: true, borderWidth: 2, borderColor: "#333", imageFit: "contain", shadow: false, title: "Clean", subtitle: "Subtitle", titleColor: "#111", titleSize: 64, titleAlign: "center", textY: 50, effects: { brightness: 100, contrast: 100, saturation: 100 } }, swatch: ["#fff", "#111"], accent: "#111" },
    ],
    appliedTemplateId: null,
    onApplyTemplate: () => {},
    onSkipTemplates: () => {},
    designTitle: "Tweak the design",
    previewTag: "Preview",
    templatesButtonLabel: "Templates",
    resetLabel: "Reset",
    backToTemplatesLabel: "Back to templates",
    continueExportLabel: "Continue to export",
    canvasGroupLabel: "Canvas",
    imageGroupLabel: "Image",
    textGroupLabel: "Text",
    fitCoverLabel: "Cover",
    fitContainLabel: "Contain",
    alignLeftLabel: "Left",
    alignCenterLabel: "Center",
    backgroundLabel: "Background",
    cornerRadiusLabel: "Corner radius",
    borderLabel: "Border",
    borderColorLabel: "Border color",
    borderWidthLabel: "Border width",
    fitLabel: "Fit",
    brightnessLabel: "Brightness",
    contrastLabel: "Contrast",
    saturationLabel: "Saturation",
    titleLabel: "Title",
    subtitleLabel: "Subtitle",
    textColorLabel: "Text color",
    titleSizeLabel: "Title size",
    positionLabel: "Position",
    alignmentLabel: "Alignment",
    shadowLabel: "Shadow",
    design: { bgColor: "#111", rounded: 0, showBorder: false, borderWidth: 0, borderColor: "#000", imageFit: "cover", shadow: true, title: "Bold", subtitle: "Subtitle", titleColor: "#fff", titleSize: 72, titleAlign: "left", textY: 60, effects: { brightness: 100, contrast: 110, saturation: 110 } },
    previewUrl:
      "data:image/svg+xml;utf8," +
      encodeURIComponent(
        '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#111"/><rect x="70" y="70" width="500" height="220" rx="12" fill="#333"/><text x="320" y="180" font-size="40" text-anchor="middle" fill="#fff">Bold</text><text x="320" y="220" font-size="20" text-anchor="middle" fill="#aaa">Subtitle</text></svg>'
      ),
    onUpdateDesign: () => {},
    onResetDesign: () => {},
    onOpenTemplates: () => {},
    exportTitle: "Export",
    downloadLabel: "Download",
    downloadAllLabel: "Download all",
    exportItems: [
      { width: 1920, height: 1080, label: "HD" },
      { width: 1280, height: 720, label: "SD" },
    ],
    exporting: false,
    onExport: () => {},
    onBackToDesign: () => {},
    onStartOver: () => {},
    footerHint: "Your images are processed in-browser.",
  };
