import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Extract",
    title: "Extract frames",
    description: "Pull stills from any video.",
    badges: [{ label: "Free", tone: "free" }],
    videoName: "demo.mp4",
    videoRef: null,
    onDropFile: () => {},
    playing: false,
    currentTime: 12,
    duration: 84,
    onTogglePlay: () => {},
    onSeek: () => {},
    onTimeUpdate: () => {},
    onLoadedMetadata: () => {},
    onEnded: () => {},
    captureLabel: "Capture frame",
    captureHint: "Pause at the moment you want.",
    onCapture: () => {},
    capturing: false,
    frameUrl: null,
    gridCount: 12,
    onGridCountChange: () => {},
    exportItems: [{ width: 1920, height: 1080, label: "1080p" }],
    exporting: false,
    onExport: () => {},
    footerHint: "Processed entirely in your browser.",
  };
