import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Images",
    title: "Generate images",
    description: "Text to image, or image to image.",
    activeTab: "text-to-image",
    tabs: [
      { key: "text-to-image", label: "Text to image" },
      { key: "image-to-image", label: "Image to image" },
    ],
    onTabChange: () => {},
    providerLabel: "Provider",
    providerOptions: [
      { value: "openai", label: "OpenAI" },
      { value: "stability", label: "Stability AI" },
      { value: "google", label: "Google" },
    ],
    provider: "openai",
    onProviderChange: () => {},
    modelLabel: "Model",
    modelOptions: [
      { value: "dall-e-3", label: "DALL·E 3" },
      { value: "sd-xl", label: "SDXL" },
    ],
    model: "dall-e-3",
    onModelChange: () => {},
    promptLabel: "Prompt",
    promptPlaceholder: "A serene mountain lake at sunset…",
    prompt: "A serene mountain lake at sunset, photorealistic",
    promptMaxLength: 1000,
    onPromptChange: () => {},
    signedIn: true,
    isGenerating: false,
    generateLabel: "Generate",
    onGenerate: () => {},
    creditsCostLabel: "1 credit",
    creditsRemainingLabel: "120 credits left",
    progressVisible: false,
    images: [
      { id: "img1", url: "", prompt: "Mountain lake", provider: "OpenAI", model: "DALL·E 3" },
      { id: "img2", url: "", prompt: "Forest path", provider: "OpenAI", model: "DALL·E 3" },
    ],
    galleryEmptyLabel: "No images yet",
    galleryReadyLabel: "Your generations",
    downloadLabel: "Download",
    downloadingId: null,
    onDownload: () => {},
    openInEditorLabel: "Open in editor",
    onOpenInEditor: () => {},
    footerHint: "Generations are stored in your gallery.",
  };
