import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Music",
    title: "Generate music",
    description: "Create original tracks from a text prompt.",
    activeMode: "quick",
    modes: [
      { key: "quick", label: "Quick", icon: "zap" },
      { key: "custom", label: "Custom", icon: "sliders" },
    ],
    onModeChange: () => {},
    providerLabel: "Provider",
    providerOptions: [
      { value: "suno", label: "Suno" },
      { value: "udio", label: "Udio" },
    ],
    provider: "suno",
    onProviderChange: () => {},
    modelLabel: "Model",
    modelOptions: [{ value: "v3", label: "v3" }, { value: "v3.5", label: "v3.5" }],
    model: "v3.5",
    onModelChange: () => {},
    customTitle: "My track",
    onCustomTitleChange: () => {},
    style: "ambient electronic",
    onStyleChange: () => {},
    lyrics: "Verse 1…",
    onLyricsChange: () => {},
    prompt: "A calm ambient track with soft pads",
    signedIn: true,
    isGenerating: false,
    generateLabel: "Generate",
    onGenerate: () => {},
    progressVisible: false,
    songs: [
      { id: "s1", title: "Neon Skyline", artist: "AI", style: "synthwave", durationLabel: "2:41", prompt: "retro synthwave" },
      { id: "s2", title: "Quiet Forest", artist: "AI", style: "ambient", durationLabel: "3:12", prompt: "calm ambient" },
    ],
    playerEmptyLabel: "No tracks yet",
    playerReadyLabel: "Your tracks",
    playingId: null,
    loadingId: null,
    onTogglePlay: () => {},
    onDownload: () => {},
    footerHint: "Tracks are added to your library.",
  };
