import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Preview",
    title: "Preview your thumbnail",
    description: "See how it looks in real products.",
    badges: [{ label: "Free", tone: "free" }],
    mode: "single",
    onModeChange: () => {},
    uploadTitle: "Upload an image",
    uploadHint: "PNG or JPG",
    uploadFormatHint: "Up to 10MB",
    uploadA: null,
    uploadB: null,
    onUploadA: () => {},
    onUploadB: () => {},
    titleValue: "My Video Title",
    titlePlaceholder: "Enter a title…",
    onTitleChange: () => {},
    channelValue: "@my-channel",
    channelPlaceholder: "Channel name…",
    onChannelChange: () => {},
    dark: true,
    onToggleDark: () => {},
    scenes: [
      { id: "feed", label: "Feed", icon: "home", size: "desktop" },
      { id: "search", label: "Search", icon: "search", size: "desktop" },
      { id: "mobile", label: "Mobile", icon: "smartphone", size: "mobile" },
      { id: "sidebar", label: "Sidebar", icon: "panel", size: "sidebar" },
    ],
    scene: "feed",
    onSceneChange: () => {},
    footerHint: "Scroll through scenes to compare.",
  };
