import type { Section } from "@template/ui";

export const props = {
    eyebrow: "Videos",
    title: "Generate videos",
    description: "Text to video with reference support.",
    activeTab: "text-to-video",
    tabs: [
      { key: "text-to-video", label: "Text to video" },
      { key: "image-to-video", label: "Image to video" },
    ],
    onTabChange: () => {},
    providerLabel: "Provider",
    providerOptions: [
      { value: "runway", label: "Runway" },
      { value: "pika", label: "Pika" },
      { value: "google", label: "Google Veo" },
    ],
    provider: "runway",
    onProviderChange: () => {},
    modelLabel: "Model",
    modelOptions: [{ value: "gen3", label: "Gen-3" }, { value: "veo2", label: "Veo 2" }],
    model: "gen3",
    onModelChange: () => {},
    promptLabel: "Prompt",
    promptPlaceholder: "A drone shot over a city…",
    prompt: "A drone shot flying over a futuristic city at dusk",
    promptMaxLength: 1000,
    onPromptChange: () => {},
    signedIn: true,
    isGenerating: false,
    generateLabel: "Generate",
    onGenerate: () => {},
    progressVisible: false,
    videos: [
      { id: "v1", url: "", prompt: "City flyover", provider: "Runway", model: "Gen-3" },
      { id: "v2", url: "", prompt: "Ocean waves", provider: "Runway", model: "Gen-3" },
    ],
    stageEmptyLabel: "No videos yet",
    stageReadyLabel: "Your videos",
    downloadLabel: "Download",
    downloadingId: null,
    onDownload: () => {},
    footerHint: "Videos are stored in your library.",
  };
