import type { Section } from "@template/ui";
import * as React from "react";

export const props = {
  className: "",
  canvasElRef: React.createRef<HTMLCanvasElement>(),
  zoom: 100,
  canvasW: 1920,
  canvasH: 1080,
  mouseX: 320,
  mouseY: 240,
  activeTool: "select",
  bgColor: "#1a1a2e",
  canUndo: true,
  canRedo: false,
  selectedObject: { id: "l2", name: "Shape", kind: "rect", x: 100, y: 80, w: 200, h: 120 },
  selectionCount: 1,
  isCropping: false,
  isEmpty: false,
  hasAutosave: false,
  gridVisible: true,
  enhance: { enhance: false, preset: "vivid" },
  layersVersion: 1,
  initialImageLoaded: false,
  t: (key: string) => key,
  brandHref: "#",
  brandName: "Studio",
  brandLogo: null,
  backHref: "#",
  previewHref: "#",
  templates: [
    { id: "t1", category: "youtube", labelKey: "bold", preview: { bg: "#7c4fff", accent: "#ff6363", text: "Bold", textColor: "#fff" } },
    { id: "t2", category: "x", labelKey: "clean", preview: { bg: "#f5f5f5", accent: "#1a1a2e", text: "Clean", textColor: "#1a1a2e" } },
  ],
  templateCategories: [
    { id: "youtube", label: "YouTube" },
    { id: "x", label: "X" },
  ],
  galleryCards: [
    { id: "c1", title: "Template 1", thumbnail: "" },
    { id: "c2", title: "Template 2", thumbnail: "" },
  ],
  aiRemoveBg: () => {},
  aiTitle: () => {},
  textStylePresets: [
    { id: "p1", name: "Bold", font: "sans", size: 48, weight: 700 },
  ],
  onSetTool: () => {},
  onSetBgColor: () => {},
  onSetBackground: () => {},
  onSetZoom: () => {},
  onFitToScreen: () => {},
  onResizeCanvas: () => {},
  onLoadImage: () => {},
  onUploadFile: () => {},
  onYouTubeFetch: () => {},
  onAddElement: () => {},
  onDeleteSelected: () => {},
  onStartCrop: () => {},
  onApplyCrop: () => {},
  onCancelCrop: () => {},
  onRestoreAutosave: () => {},
  onDismissAutosave: () => {},
  onApplyTemplate: () => {},
  onApplyTemplateById: () => {},
  onUndo: () => {},
  onRedo: () => {},
  onGetLayers: () => [
    { id: "l1", name: "Background", kind: "rect", visible: true, locked: false },
    { id: "l2", name: "Shape", kind: "rect", visible: true, locked: false },
    { id: "l3", name: "Text", kind: "text", visible: true, locked: false },
  ],
  onSelectLayer: () => {},
  onSelectLayerMulti: () => {},
  onMoveLayer: () => {},
  onReorderLayers: () => {},
  onGroupSelected: () => {},
  onUngroupSelected: () => {},
  onAlignSelected: () => {},
  onDistributeSelected: () => {},
  onDuplicateSelected: () => {},
  onFlipSelected: () => {},
  onZOpSelected: () => {},
  onToggleLayer: () => {},
  onToggleLockLayer: () => {},
  onDeleteLayer: () => {},
  onToggleGrid: () => {},
  onUpdateSelectedObject: () => {},
  onApplyStylePreset: () => {},
  onSetEnhance: () => {},
  onExportImage: () => {},
  ctxMenu: null,
  onCloseContextMenu: () => {},
  exportResult: null,
  onCloseExport: () => {},
  onGrabGallery: () => {},
};
