import type { Section } from "@template/ui";
import * as React from "react";

const EN: Record<string, string> = {
  mode_label: "Mode",
  tone_label: "Tone",
  length_label: "Length",
  strength_label: "Strength",
  cleaning_options: "Cleaning options",
  options_label: "Options",
  input_label: "Input",
  input_placeholder: "Paste AI-generated text here…",
  output_label: "Output",
  run_analysis: "Run analysis",
  clear: "Clear",
  copy: "Copy",
  copied: "Copied",
  auto_convert: "Auto-convert",
  advanced_options: "Advanced options",
  fallback_notice: "Running in local fallback mode.",
  security_note: "Text never leaves your device.",
};

export const props = {
  section: { id: "cleaner", title: "AI Text Cleaner", description: "Humanize and clean AI-generated text." },
  fullscreen: true,
  input: "The quick brown fox jumps over the lazy dog. Moreover, it is important to note that the team was able to complete the task efficiently and effectively, leveraging a wide array of tools.",
  onInputChange: () => {},
  mode: "humanize",
  onModeChange: () => {},
  tone: "natural",
  onToneChange: () => {},
  length: "same",
  onLengthChange: () => {},
  strength: "standard",
  onStrengthChange: () => {},
  options: ["trimWhitespace", "normalizeDashes", "convertEllipsis"],
  onOptionsChange: () => {},
  outputView: "changes",
  output: "The quick brown fox jumps over the lazy dog. The team completed the task efficiently.",
  inputCount: 142,
  outputCount: 118,
  error: "",
  copied: false,
  shareCopied: false,
  busy: false,
  showAiHint: true,
  activeDiffParts: [
    { value: "The quick brown fox jumps over the lazy dog. " },
    { value: "Moreover, it is important to note that ", removed: true },
    { value: "The team completed the task efficiently." },
  ],
  activeHasChanges: true,
  analyzeResult: null,
  isRewriting: false,
  fallbackNotice: false,
  showAdvancedOptions: false,
  onToggleAdvancedOptions: () => {},
  contextMode: "auto",
  detectedContextMode: "general",
  typeLabels: { repetition: "Repetition", passive: "Passive voice" },
  severityLabels: { high: "High", medium: "Medium", low: "Low" },
  onClear: () => {},
  onCopy: () => {},
  onAnalyze: () => {},
  onFixWithAi: () => {},
  onContextModeChange: () => {},
  onExportMarkdown: () => {},
  onExportPdf: () => {},
  onShareLink: () => {},
  t: (key: string) => EN[key] ?? key,
  modeOptions: [
    { value: "humanize", label: "Humanize" },
    { value: "simplify", label: "Simplify" },
    { value: "professional", label: "Professional" },
    { value: "grammar", label: "Grammar" },
  ],
  toneOptions: [
    { value: "natural", label: "Natural" },
    { value: "confident", label: "Confident" },
    { value: "friendly", label: "Friendly" },
  ],
  lengthOptions: [
    { value: "same", label: "Same" },
    { value: "shorter", label: "Shorter" },
    { value: "longer", label: "Longer" },
  ],
  strengthOptions: [
    { value: "light", label: "Light" },
    { value: "standard", label: "Standard" },
    { value: "strong", label: "Strong" },
  ],
  optionLabels: {
    trimWhitespace: "Trim whitespace",
    normalizeDashes: "Normalize dashes",
    convertEllipsis: "Convert ellipsis",
    removeAsterisks: "Remove asterisks",
  },
};
