/**
 * Semi theme manifest — which implementations back each contract key for the
 * `semi` theme (@douyinfe/semi-ui).
 *
 * The semi implementations (components/sections/pages, see `./index.tsx`)
 * live in this directory; this file wires them into the registry (the
 * registry aggregator, `../../registry.ts`, assembles this into the
 * `registry` map).
 *
 * Missing keys (ToolHeader/ToolFooter/ToolSettings/DualCta) are not registered
 * here and fall back to the default theme via the resolvers.
 */
import {
  Button as SemiButton,
  Badge as SemiBadge,
  Card as SemiCard,
  Input as SemiInput,
  Textarea as SemiTextarea,
  Switch as SemiSwitch,
  Progress as SemiProgress,
  Tooltip as SemiTooltip,
  Skeleton as SemiSkeleton,
  Select as SemiSelect,
  Toggle as SemiToggle,
  ToggleGroup as SemiToggleGroup,
  BareTextarea as SemiBareTextarea,
  Dropdown as SemiDropdown,
  Dialog as SemiDialog,
  PromoModal as SemiPromoModal,
  HintBanner as SemiHintBanner,
  Stack as SemiStack,
  Cluster as SemiCluster,
  Grid as SemiGrid,
  Divider as SemiDivider,
  Label as SemiLabel,
  Avatar as SemiAvatar,
  Box as SemiBox,
  IconFrame as SemiIconFrame,
  InputNumber as SemiInputNumber,
  Slider as SemiSlider,
  Tag as SemiTag,
  Tabs as SemiTabs,
  Empty as SemiEmpty,
  Spin as SemiSpin,
  Steps as SemiSteps,
  Table as SemiTable,
  Descriptions as SemiDescriptions,
  UploadZone as SemiUploadZone,
  Banner as SemiBanner,
  Header as SemiHeader,
  Footer as SemiFooter,
  LayoutShell as SemiLayoutShell,
  Navigation as SemiNavigation,
  Image as SemiImage,
  ColorPicker as SemiColorPicker,
  Collapse as SemiCollapse,
  List as SemiList,
  Carousel as SemiCarousel,
  Timeline as SemiTimeline,
  CopyText as SemiCopyText,
  ToolPage as SemiToolPage,
  ConsoleLayout as SemiConsoleLayout,
} from "./index";
import {
  Hero as SemiHero,
  Features as SemiFeatures,
  FeaturesGrid as SemiFeaturesGrid,
  FeaturesStep as SemiFeaturesStep,
  FeaturesAccordion as SemiFeaturesAccordion,
  FeaturesCompare as SemiFeaturesCompare,
  FeaturesFlow as SemiFeaturesFlow,
  FeaturesList as SemiFeaturesList,
  ToolsGrid as SemiToolsGrid,
  Showcases as SemiShowcases,
  Stats as SemiStats,
  Logos as SemiLogos,
  Testimonials as SemiTestimonials,
  Faq as SemiFaq,
  Cta as SemiCta,
  Subscribe as SemiSubscribe,
  Pricing as SemiPricing,
  ToolHero as SemiToolHero,
  PageHeader as SemiPageHeader,
  DashboardOverview as SemiDashboardOverview,
  SettingsOverview as SemiSettingsOverview,
  ActivityOverview as SemiActivityOverview,
  ChatWorkbench as SemiChatWorkbench,
  ChatHistory as SemiChatHistory,
  MusicGeneratorStudio as SemiMusicGeneratorStudio,
  ImageGeneratorStudio as SemiImageGeneratorStudio,
  VideoGeneratorStudio as SemiVideoGeneratorStudio,
  ResizeWorkbench as SemiResizeWorkbench,
  CompressWorkbench as SemiCompressWorkbench,
  ExtractWorkbench as SemiExtractWorkbench,
  DownloadWorkbench as SemiDownloadWorkbench,
  PreviewWorkbench as SemiPreviewWorkbench,
  DesignerStudio as SemiDesignerStudio,
  HeroLive as SemiHeroLive,
  Workbench as SemiWorkbench,
} from "./index";

import type { ThemeManifest } from "../../registry-types";

export const semiManifest: ThemeManifest = {
  name: "semi",
  components: {
    Button: SemiButton,
    Badge: SemiBadge,
    Card: SemiCard,
    Input: SemiInput,
    Textarea: SemiTextarea,
    Switch: SemiSwitch,
    Progress: SemiProgress,
    Tooltip: SemiTooltip,
    Skeleton: SemiSkeleton,
    Header: SemiHeader,
    Footer: SemiFooter,
    Box: SemiBox,
    Label: SemiLabel,
    Avatar: SemiAvatar,
    Dialog: SemiDialog,
    PromoModal: SemiPromoModal,
    HintBanner: SemiHintBanner,
    Dropdown: SemiDropdown,
    Stack: SemiStack,
    Cluster: SemiCluster,
    Grid: SemiGrid,
    Divider: SemiDivider,
    Select: SemiSelect,
    Toggle: SemiToggle,
    ToggleGroup: SemiToggleGroup,
    BareTextarea: SemiBareTextarea,
    IconFrame: SemiIconFrame,
    InputNumber: SemiInputNumber,
    Slider: SemiSlider,
    Tag: SemiTag,
    Tabs: SemiTabs,
    Empty: SemiEmpty,
    Spin: SemiSpin,
    Steps: SemiSteps,
    Table: SemiTable,
    Descriptions: SemiDescriptions,
    UploadZone: SemiUploadZone,
    Banner: SemiBanner,
    Layout: SemiLayoutShell,
    Navigation: SemiNavigation,
    Image: SemiImage,
    ColorPicker: SemiColorPicker,
    Collapse: SemiCollapse,
    List: SemiList,
    Carousel: SemiCarousel,
    Timeline: SemiTimeline,
    CopyText: SemiCopyText,
    ToolPage: SemiToolPage,
    ConsoleLayout: SemiConsoleLayout,
  },
  sections: {
    Hero: SemiHero,
    Features: SemiFeatures,
    FeaturesGrid: SemiFeaturesGrid,
    FeaturesStep: SemiFeaturesStep,
    FeaturesAccordion: SemiFeaturesAccordion,
    FeaturesCompare: SemiFeaturesCompare,
    FeaturesFlow: SemiFeaturesFlow,
    FeaturesList: SemiFeaturesList,
    ToolsGrid: SemiToolsGrid,
    Showcases: SemiShowcases,
    Stats: SemiStats,
    Logos: SemiLogos,
    Testimonials: SemiTestimonials,
    Faq: SemiFaq,
    Cta: SemiCta,
    Subscribe: SemiSubscribe,
    Pricing: SemiPricing,
    ToolHero: SemiToolHero,
    PageHeader: SemiPageHeader,
    DashboardOverview: SemiDashboardOverview,
    SettingsOverview: SemiSettingsOverview,
    ActivityOverview: SemiActivityOverview,
    ChatWorkbench: SemiChatWorkbench,
    ChatHistory: SemiChatHistory,
    MusicGeneratorStudio: SemiMusicGeneratorStudio,
    ImageGeneratorStudio: SemiImageGeneratorStudio,
    VideoGeneratorStudio: SemiVideoGeneratorStudio,
    ResizeWorkbench: SemiResizeWorkbench,
    CompressWorkbench: SemiCompressWorkbench,
    ExtractWorkbench: SemiExtractWorkbench,
    DownloadWorkbench: SemiDownloadWorkbench,
    PreviewWorkbench: SemiPreviewWorkbench,
    DesignerStudio: SemiDesignerStudio,
    HeroLive: SemiHeroLive,
    Workbench: SemiWorkbench,
  },
};
