/**
 * Whitelist of Lucide icons used across the site.
 *
 * SmartIcon used to `await import('lucide-react')` dynamically, which pulled
 * the ENTIRE lucide icon library (~600 SVGs, ~1.9MB) into the shared chunk.
 * This module statically imports only the icons the app actually renders, so
 * the bundler tree-shakes to those few KB — the same pattern as smart-icon-ri.
 *
 * There is intentionally NO lazy `import('lucide-react')` fallback here: the
 * moment a module is both statically and dynamically imported, bundlers hoist
 * the whole library back into the eager graph. If a new icon is needed, add
 * its named import below.
 *
 * The set covers:
 * - Every `import { X } from 'lucide-react'` in src/ and packages/ui/ (74 names)
 * - The runtime names SmartIcon receives via `name="..."` that don't start with
 *   "Ri" (ArrowLeft / Menu / Search — resolved to HelpCircle when unknown)
 */
import { ComponentType } from 'react';
import {
  AlertTriangleIcon,
  ArrowLeft,
  ArrowRight,
  ArrowRightIcon,
  BrainCircuitIcon,
  Calendar,
  CalendarIcon,
  Check,
  CheckCircle2,
  CheckCircleIcon,
  CheckIcon,
  ChefHatIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Clock,
  ClockIcon,
  Coins,
  CopyIcon,
  Crop,
  Download,
  Eye,
  FlameIcon,
  Globe,
  GlobeIcon,
  HeartIcon,
  HelpCircle,
  ImageIcon,
  InfoIcon,
  Languages,
  LayoutDashboard,
  LeafIcon,
  LightbulbIcon,
  ListIcon,
  Loader,
  Loader2,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointer2,
  Pause,
  Play,
  Printer,
  Redo2,
  RefreshCcwIcon,
  RotateCw,
  ScanLine,
  Search,
  SendHorizonal,
  Share2,
  Sparkles,
  Star,
  StarIcon,
  SunDim,
  TimerIcon,
  Trash,
  Trash2,
  Type,
  Undo2,
  User,
  UsersIcon,
  UtensilsIcon,
  Volume2,
  VolumeX,
  X,
  XIcon,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

/** Static (tree-shaken) registry of all Lucide icons the app renders. */
export const lucideIconWhitelist: Record<string, ComponentType<any>> = {
  AlertTriangleIcon,
  ArrowLeft,
  ArrowRight,
  ArrowRightIcon,
  BrainCircuitIcon,
  Calendar,
  CalendarIcon,
  Check,
  CheckCircle2,
  CheckCircleIcon,
  CheckIcon,
  ChefHatIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Clock,
  ClockIcon,
  Coins,
  CopyIcon,
  Crop,
  Download,
  Eye,
  FlameIcon,
  Globe,
  GlobeIcon,
  HeartIcon,
  HelpCircle,
  ImageIcon,
  InfoIcon,
  Languages,
  LayoutDashboard,
  LeafIcon,
  LightbulbIcon,
  ListIcon,
  Loader,
  Loader2,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointer2,
  Pause,
  Play,
  Printer,
  Redo2,
  RefreshCcwIcon,
  RotateCw,
  ScanLine,
  Search,
  SendHorizonal,
  Share2,
  Sparkles,
  Star,
  StarIcon,
  SunDim,
  TimerIcon,
  Trash,
  Trash2,
  Type,
  Undo2,
  User,
  UsersIcon,
  UtensilsIcon,
  Volume2,
  VolumeX,
  X,
  XIcon,
  Zap,
  ZoomIn,
  ZoomOut,
};
